# Generated by Django 4.2.27 on 2026-01-17 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='about_me',
            new_name='about',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='profession',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='job',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='language',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='theme',
        ),
        migrations.AddField(
            model_name='profile',
            name='alcohol',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='cleanliness',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='gamer',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='guests_parties',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='introvert_extrovert',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='looking_for_housing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='profile',
            name='noise_tolerance',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pets',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_age_range',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='sleep_schedule',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='smoking',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='work_from_home',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
