# Generated by Django 4.2.27 on 2026-01-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_about_me_profile_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email & Password'), ('google', 'Google'), ('apple', 'Apple')], default='email', max_length=20),
        ),
    ]
