# Generated by Django 4.2.27 on 2026-01-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_city_listing_region'),
        ('users', '0004_profile_auth_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_listings',
            field=models.ManyToManyField(blank=True, help_text='Избранные объявления', related_name='favorited_by', to='listings.listing'),
        ),
    ]
