# Generated by Django 4.2.27 on 2026-01-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_favorite_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_profiles',
            field=models.ManyToManyField(blank=True, help_text='Избранные соседи', related_name='favorited_neighbors', to='users.profile'),
        ),
    ]
