# Generated by Django 4.2.27 on 2026-03-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_remove_listing_property_type_and_more'),
        ('users', '0016_remove_profile_pensioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pensioner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='favorite_listings',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='listings.listing'),
        ),
    ]
