# Generated by Django 4.2.27 on 2026-03-24 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_pensioner_alter_profile_favorite_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='moderation_strikes',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
