# Generated by Django 4.2.27 on 2026-04-09 20:35

from django.db import migrations, models


def seed_team_members(apps, schema_editor):
    TeamMember = apps.get_model("users", "TeamMember")
    if TeamMember.objects.exists():
        return
    TeamMember.objects.bulk_create(
        [
            TeamMember(
                sort_order=0,
                name="Michal Krechler",
                email="info@flatfly.cz",
                phone="+420777123456",
                website="https://flatfly.cz",
                role_cz="Zakladatel",
                role_en="Founder",
                role_ru="Основатель",
            ),
            TeamMember(
                sort_order=1,
                name="Tomáš Hájek",
                email="info@flatfly.cz",
                phone="+420777123456",
                website="",
                role_cz="Designér",
                role_en="Designer",
                role_ru="Дизайнер",
            ),
            TeamMember(
                sort_order=2,
                name="Bogdan Rassovskiy",
                email="info@flatfly.cz",
                phone="+420777123456",
                website="https://flatfly.cz",
                role_cz="IT",
                role_en="IT",
                role_ru="IT",
            ),
        ]
    )


def unseed_team_members(apps, schema_editor):
    TeamMember = apps.get_model("users", "TeamMember")
    TeamMember.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_profile_cover_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveSmallIntegerField(db_index=True, default=0)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=64)),
                ('website', models.URLField(blank=True, default='')),
                ('role_cz', models.CharField(max_length=120)),
                ('role_en', models.CharField(max_length=120)),
                ('role_ru', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'Team member (homepage)',
                'verbose_name_plural': 'Team members (homepage)',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed_team_members, unseed_team_members),
    ]
