# Generated by Django 4.2.29 on 2026-04-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_profile_email_verified_profile_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verification_required',
            field=models.BooleanField(default=False, help_text='If True, login is blocked until email is verified. Set only for new email signups.'),
        ),
    ]
