# Generated by Django 4.2.27 on 2026-01-18 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='layout',
        ),
        migrations.AddField(
            model_name='listing',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='has_roommates',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='pets_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='rental_period',
            field=models.CharField(choices=[('SHORT', 'Short term'), ('LONG', 'Long term'), ('BOTH', 'Both')], default='LONG', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='smoking_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='utilities_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('APARTMENT', 'Apartment'), ('ROOM', 'Room'), ('NEIGHBOUR', 'Neighbour')], max_length=20),
        ),
    ]
