# Generated by Django 4.2.27 on 2026-01-18 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_listing_layout_listing_amenities_listing_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='city',
        ),
        migrations.AddField(
            model_name='listing',
            name='region',
            field=models.CharField(choices=[('PRAGUE', 'Praha'), ('STREDOCESKY', 'Středočeský kraj'), ('JIHOCESKY', 'Jihočeský kraj'), ('PLZENSKY', 'Plzeňský kraj'), ('KARLOVARSKY', 'Karlovarský kraj'), ('USTECKY', 'Ústecký kraj'), ('LIBERECKY', 'Liberecký kraj'), ('KRALOVEHRADECKY', 'Královéhradecký kraj'), ('PARDUBICKY', 'Pardubický kraj'), ('VYSOCINA', 'Vysočina'), ('JIHOMORAVSKY', 'Jihomoravský kraj'), ('OLOMOUCKY', 'Olomoucký kraj'), ('ZLINSKY', 'Zlínský kraj'), ('MORAVSKOSLEZSKY', 'Moravskoslezský kraj')], default='PRAGUE', max_length=32),
            preserve_default=False,
        ),
    ]
