# Generated by Django 5.2.11 on 2026-02-03 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listing_city_listing_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='size',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='type',
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='condition_state',
            field=models.CharField(blank=True, choices=[('VELMI_DOBRY', 'Velmi dobrý'), ('DOBRY', 'Dobrý'), ('SPATNY', 'Špatný'), ('NOVOSTAVBA', 'Novostavba'), ('VE_VYSTAVBE', 'Ve výstavbě'), ('PRED_REKONSTRUKCI', 'Před rekonstrukcí'), ('V_REKONSTRUKCI', 'V rekonstrukci'), ('PO_REKONSTRUKCI', 'Po rekonstrukci')], max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='country',
            field=models.CharField(default='CZ', max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='currency',
            field=models.CharField(choices=[('CZK', 'CZK'), ('EUR', 'EUR'), ('USD', 'USD')], default='CZK', max_length=3),
        ),
        migrations.AddField(
            model_name='listing',
            name='energy_class',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='geo_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='geo_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_3d_tour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_atm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_bus_stop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_floorplan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_general_practitioner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_kindergarten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_metro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_playground',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_post_office',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_primary_school',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_small_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_supermarket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_train_station',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_vet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='has_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.CharField(choices=[('BYT', 'Byt'), ('DUM', 'Dům'), ('APARTMENT', 'Apartment'), ('ROOM', 'Room'), ('NEIGHBOUR', 'Neighbour')], default='APARTMENT', max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='usable_area',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
