# Generated by Django 5.2.11 on 2026-02-03 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_listing_size_remove_listing_type_listing_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
