# Generated by Django 4.2.27 on 2026-03-15 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_listing_preferred_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='property_type',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='usable_area',
        ),
        migrations.AddField(
            model_name='listing',
            name='size',
            field=models.IntegerField(blank=True, db_column='usable_area', null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.CharField(choices=[('BYT', 'Byt'), ('DUM', 'Dům'), ('APARTMENT', 'Apartment'), ('ROOM', 'Room'), ('NEIGHBOUR', 'Kolej')], db_column='property_type', default='APARTMENT', max_length=20),
        ),
    ]
