# Generated by Django 4.2.27 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0019_listingreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="telegram_channel_message_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="listing",
            name="telegram_channel_posted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]

