# Generated by Django 4.2.27 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0020_listing_telegram_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="telegram_channel_message_ids",
            field=models.JSONField(blank=True, default=list),
        ),
    ]

