# Generated by Django 4.2.27 on 2026-01-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='size',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
