# Generated by Django 4.2.27 on 2026-01-21 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('date', models.CharField(max_length=50)),
                ('content_en', models.TextField(blank=True, help_text='Content in English (HTML allowed)')),
                ('content_ru', models.TextField(blank=True, help_text='Content in Russian (HTML allowed)')),
                ('content_cz', models.TextField(blank=True, help_text='Content in Czech (HTML allowed)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-created_at'],
            },
        ),
    ]
