# Generated by Django 4.2.27 on 2026-02-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_id', models.PositiveIntegerField(db_index=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('cz', 'Czech')], max_length=2)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('keys', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['faq_id', 'language'],
                'constraints': [
                    models.UniqueConstraint(fields=('faq_id', 'language'), name='unique_faq_id_language'),
                ],
            },
        ),
    ]
