# Generated by Django 4.2.27 on 2026-02-18 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_launchsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
