# Generated by Django 4.2.27 on 2026-03-24 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0002_chatreport_chatblock_chatblock_uniq_chat_block_pair'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatreport',
            name='resolution_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='chatreport',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatreport',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_reports_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='chatreport',
            name='strike_applied',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ModerationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_messages_created', to=settings.AUTH_USER_MODEL)),
                ('linked_chat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_messages', to='chats.chat')),
                ('linked_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_messages', to='chats.message')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderation_messages_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at', '-id'],
            },
        ),
    ]
