# Generated by Django 4.2.27 on 2026-03-24 07:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0019_listingreport'),
        ('chats', '0003_chatreport_resolution_note_chatreport_reviewed_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RejectedImageModerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('avatar', 'Avatar'), ('listing', 'Listing image')], max_length=32)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('raw_scores', models.JSONField(blank=True, default=dict)),
                ('provider', models.CharField(default='google_vision', max_length=64)),
                ('raw_labels', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_image_logs', to='listings.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_image_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
