# Generated by Django 4.2.27 on 2026-03-25 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0004_rejectedimagemoderationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModerationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('local_opennsfw2', 'Local OpenNSFW2')], default='local_opennsfw2', max_length=64)),
                ('metric', models.CharField(choices=[('nsfw_probability', 'NSFW probability')], default='nsfw_probability', max_length=64)),
                ('threshold', models.FloatField(default=0.65)),
                ('reasons', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'provider', 'metric', 'threshold', 'id'],
            },
        ),
    ]
