# Generated by Django 4.2.27 on 2026-03-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_imagemoderationrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemoderationrule',
            name='metric',
            field=models.CharField(choices=[('nsfw_probability', 'NSFW probability'), ('nudity_raw', 'Sightengine nudity raw'), ('nudity_partial', 'Sightengine nudity partial')], default='nsfw_probability', max_length=64),
        ),
        migrations.AlterField(
            model_name='imagemoderationrule',
            name='provider',
            field=models.CharField(choices=[('local_opennsfw2', 'Local OpenNSFW2'), ('sightengine', 'Sightengine')], default='local_opennsfw2', max_length=64),
        ),
    ]
