# Generated by Django 4.2.27 on 2026-03-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0006_alter_imagemoderationrule_metric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemoderationrule',
            name='metric',
            field=models.CharField(choices=[('nsfw_probability', 'NSFW probability'), ('nudity_raw', 'Sightengine nudity raw'), ('nudity_partial', 'Sightengine nudity partial'), ('offensive_nazi', 'Sightengine offensive nazi'), ('offensive_terrorist', 'Sightengine offensive terrorist'), ('offensive_supremacist', 'Sightengine offensive supremacist'), ('offensive_offensive', 'Sightengine offensive content')], default='nsfw_probability', max_length=64),
        ),
    ]
