# Generated by Django 4.2.27 on 2026-03-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0007_alter_imagemoderationrule_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemoderationrule',
            name='metric',
            field=models.CharField(choices=[('nsfw_probability', 'NSFW probability'), ('nudity_raw', 'Sightengine nudity raw'), ('nudity_partial', 'Sightengine nudity partial'), ('nudity_sexual_activity', 'Sightengine nudity sexual activity'), ('nudity_sexual_display', 'Sightengine nudity sexual display'), ('nudity_erotica', 'Sightengine nudity erotica'), ('nudity_suggestive', 'Sightengine nudity suggestive'), ('offensive_nazi', 'Sightengine offensive nazi'), ('offensive_terrorist', 'Sightengine offensive terrorist'), ('offensive_supremacist', 'Sightengine offensive supremacist'), ('offensive_offensive', 'Sightengine offensive content'), ('weapon', 'Sightengine weapon'), ('weapon_firearm', 'Sightengine weapon firearm'), ('weapon_knife', 'Sightengine weapon knife'), ('gore_prob', 'Sightengine gore prob'), ('drugs', 'Sightengine drugs'), ('recreational_drugs', 'Sightengine recreational drugs')], default='nsfw_probability', max_length=64),
        ),
    ]
